[package]
name = "hello-world"
version = "0.1.0"
authors = ["leang27 <52003343+leang27@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {git = "https://github.com/hecrj/iced.git"}
iced_graphics = {git = "https://github.com/hecrj/iced.git"}
chrono = "0.4"
rand = "0.7.3"
iced_futures = "0.1.2"
async-std = {version = "1.6.5", features = ["unstable"]}
iced_native =  {git = "https://github.com/hecrj/iced.git"}
iced_wgpu =  {git = "https://github.com/hecrj/iced.git"}