#[derive(Debug, Clone, Copy, Hash)]
pub enum IconBrands {
    Codepen,
    Cpanel,
    Viber,
    PiedPiperLogo,
    OldRepublic,
    Java,
    AlternatePiedPiperLogo,
    AppNet,
    Umbraco,
    StumbleuponLogo,
    Themeco,
    Adobe,
    Opencart,
    DinerSClubCreditCard,
    CreativeCommonsNoDerivativeWorks,
    Telegram,
    CreativeCommons,
    Quinscape,
    Figma,
    Renren,
    AmazonWebServicesAws,
    Algolia,
    HackerNewsSquare,
    Dev,
    GripfireInc,
    Angellist,
    Teamspeak,
    Ember,
    AmazonPay,
    Joget,
    TencentWeibo,
    Artstation,
    Freebsd,
    Contao,
    GoogleDrive,
    Vaadin,
    Cuttlefish,
    Periscope,
    Searchengin,
    TheRedYeti,
    Neos,
    GooglePlus,
    FacebookMessenger,
    Openid,
    Viacoin,
    Quora,
    XingSquare,
    Pinterest,
    Autoprefixer,
    AlternateFontAwesome,
    StripeCreditCard,
    Strava,
    Snapchat,
    InternetExplorer,
    Invision,
    GoodreadsG,
    Opera,
    DiggLogo,
    Waze,
    Python,
    YandexInternational,
    Rockrms,
    WeixinWechat,
    Mendeley,
    Salesforce,
    Simplybuilt,
    RebelAlliance,
    Angular,
    FontAwesomeFlag,
    CanadianMapleLeaf,
    Elementor,
    Centos,
    Ravelry,
    LastFm,
    AmazonPayCreditCard,
    FacebookF,
    Dashcube,
    Yelp,
    EnviraGallery,
    JoomlaLogo,
    CriticalRole,
    AlternateCss3Logo,
    Line,
    JavascriptJs,
    Ups,
    Evernote,
    Flipboard,
    Airbnb,
    Instagram,
    Goodreads,
    Confluence,
    RedditLogo,
    TumblrSquare,
    Hips,
    VisaCreditCard,
    Playstation,
    Nutritionix,
    FonticonsFi,
    GlideG,
    Slideshare,
    Sketch,
    Delicious,
    Laravel,
    StripeS,
    EdgeBrowser,
    Pagelines,
    MaterialDesignForBootstrap,
    Swift,
    Superpowers,
    StackOverflow,
    Buysellads,
    HackerNews,
    Steam,
    BloggerB,
    PhoenixSquadron,
    Uber,
    ItunesNote,
    Odnoklassniki,
    GoogleWallet,
    Discord,
    Ns8,
    OptinMonster,
    Speakap,
    Buffer,
    Jenkis,
    Keybase,
    Firstdraft,
    Suse,
    Resolving,
    GithubSquare,
    WordpressSimple,
    Microsoft,
    Ubuntu,
    Mailchimp,
    Firefox,
    Adversal,
    Fedora,
    VueJs,
    Apple,
    Sourcetree,
    Foursquare,
    Blackberry,
    Qq,
    Weibo,
    Less,
    Gitlab,
    ItchIo,
    Php,
    Dochub,
    Chrome,
    StumbleuponCircle,
    AcquisitionsIncorporated,
    Megaport,
    Affiliatetheme,
    IosAppStore,
    Servicestack,
    Mastodon,
    NodeJsJs,
    FreeCodeCamp,
    NodeJs,
    WordpressLogo,
    TwitterSquare,
    ProductHunt,
    Aviato,
    Pushed,
    Mrt,
    Sellcast,
    Lyft,
    Ethereum,
    CreativeCommonsSampling,
    Markdown,
    Napster,
    Ello,
    CreativeCommonsShareAlike,
    Bootstrap,
    Fulcrum,
    Windows,
    ShirtsInBulk,
    Gulp,
    Vimeo,
    RocketChat,
    WizardsOfTheCoast,
    Android,
    Sistrix,
    TradeFederation,
    Zhihu,
    Video,
    Wpbeginner,
    Atlassian,
    Ebay,
    Medium,
    CreativeCommonsShare,
    Skyatlas,
    Safari,
    FortAwesome,
    Mixcloud,
    RProject,
    Audible,
    GetPocket,
    OpenSourceInitiative,
    Erlang,
    Bitcoin,
    GitAlt,
    Dyalog,
    AlternateCreativeCommonsPublicDomain,
    PinterestP,
    GoogleLogo,
    Npm,
    FacebookSquare,
    Jira,
    StackExchange,
    Hackerrank,
    Sass,
    PiedPiperHat,
    Fly,
    Css3Logo,
    Deviantart,
    GgCurrency,
    GooglePlusSquare,
    Html5Logo,
    BRomBelExperteGmbhCoKg,
    RaspberryPi,
    AlternateGithub,
    Leanpub,
    Forumbee,
    DigitalOcean,
    Bitbucket,
    SteamSymbol,
    Twitch,
    Blogger,
    Spotify,
    YahooLogo,
    Yandex,
    CottonBureau,
    Jsfiddle,
    Etsy,
    Phabricator,
    Squarespace,
    RedRiver,
    ConnectDevelop,
    KickstarterK,
    Expeditedssl,
    ApplePayCreditCard,
    Itunes,
    Vine,
    DDBeyond,
    Bimobject,
    Bluetooth,
    Earlybirds,
    ApplePay,
    SlackHashtag,
    Linode,
    GitSquare,
    Uniregistry,
    AlternateFortAwesome,
    GgCurrencyCircle,
    PennyArcade,
    PaypalCreditCard,
    Researchgate,
    Tripadvisor,
    Themeisle,
    Skype,
    StickerMule,
    Sellsy,
    Kaggle,
    Bity,
    Dhl,
    FirstOrder,
    RedditSquare,
    Weebly,
    Cloudversify,
    Bandcamp,
    Grunt,
    Xbox,
    AccessibleIcon,
    CreativeCommonsRemix,
    Glide,
    DribbbleSquare,
    Symfony,
    Mix,
    Bluetooth2,
    Meetup,
    SpeakerDeck,
    Monero,
    LastFmSquare,
    GooglePlay,
    Diaspora,
    Docker,
    CreativeCommonsCc0,
    Patreon,
    JediOrder,
    DeployDog,
    Reacteurope,
    Untappd,
    BattleNet,
    Gitkraken,
    Houzz,
    YoutubeSquare,
    LinkedinIn,
    RevIo,
    Usb,
    Accusoft,
    Deskpro,
    Replyd,
    CreativeCommonsAttribution,
    Centercode,
    GalacticEmpire,
    Nimblr,
    Page4Corporation,
    Uikit,
    CreativeCommonsNoncommercial,
    Korvue,
    Hireahelper,
    Tumblr,
    CreativeCommonsNoncommercialYenSign,
    Soundcloud,
    AngryCreative,
    Yammer,
    Fedex,
    Linux,
    Intercom,
    VideoSquare,
    Discourse,
    Modx,
    Hornbill,
    GratipayGittip,
    Alipay,
    ApperSystemsAb,
    Linkedin,
    Amazon,
    DiscoverCreditCard,
    Yarn,
    Draft2digital,
    Vnv,
    Kickstarter,
    WikipediaW,
    VimeoSquare,
    CreativeCommonsNoncommercialEuroSign,
    WolfPackBattalion,
    StudioVinari,
    Cloudsmith,
    MastercardCreditCard,
    BuyNLarge,
    Vk,
    Hooli,
    Amilia,
    Gofore,
    Redhat,
    OdnoklassnikiSquare,
    Gitter,
    Dribbble,
    Mandalorian,
    Yoast,
    PhoenixFramework,
    Chromecast,
    DrupalLogo,
    Dropbox,
    Medapps,
    Shopware,
    Hotjar,
    Hubspot,
    ThinkPeaks,
    Flickr,
    Whmcs,
    Mizuni,
    Avianex,
    Wpforms,
    Magento,
    AsymmetrikLtd,
    Staylinked,
    Typo3,
    Behance,
    WhatSApp,
    FantasyFlightGames,
    FontAwesomeBlackTie,
    CodiePie,
    Stackpath,
    Xing,
    Maxcdn,
    Twitter,
    _500px,
    Facebook,
    Supple,
    Imdb,
    DungeonsDragons,
    WhatSAppSquare,
    CreativeCommons2,
    Orcid,
    Wix,
    JavascriptJsSquare,
    React,
    CloudscaleCh,
    Trello,
    AlternateFirstOrder,
    PinterestSquare,
    UnitedStatesPostalService,
    CreativeCommonsPublicDomain,
    Readme,
    UsSunnahFoundation,
    Github,
    AmericanExpressCreditCard,
    Scribd,
    Ioxhost,
    Keycdn,
    Schlix,
    SnapchatSquare,
    SteamSquare,
    AppStore,
    GalacticSenate,
    Palfed,
    Youtube,
    Wpressr,
    Wpexplorer,
    BehanceSquare,
    Grav,
    Sith,
    JcbCreditCard,
}

fn icon_unicode(icon: IconBrands) -> char {
    use self::IconBrands::*;
    match icon {
        Codepen => '\u{f1cb}',
        Cpanel => '\u{f388}',
        Viber => '\u{f409}',
        PiedPiperLogo => '\u{f1a7}',
        OldRepublic => '\u{f510}',
        Java => '\u{f4e4}',
        AlternatePiedPiperLogo => '\u{f1a8}',
        AppNet => '\u{f170}',
        Umbraco => '\u{f8e8}',
        StumbleuponLogo => '\u{f1a4}',
        Themeco => '\u{f5c6}',
        Adobe => '\u{f778}',
        Opencart => '\u{f23d}',
        DinerSClubCreditCard => '\u{f24c}',
        CreativeCommonsNoDerivativeWorks => '\u{f4eb}',
        Telegram => '\u{f2c6}',
        CreativeCommons => '\u{f25e}',
        Quinscape => '\u{f459}',
        Figma => '\u{f799}',
        Renren => '\u{f18b}',
        AmazonWebServicesAws => '\u{f375}',
        Algolia => '\u{f36c}',
        HackerNewsSquare => '\u{f3af}',
        Dev => '\u{f6cc}',
        GripfireInc => '\u{f3ac}',
        Angellist => '\u{f209}',
        Teamspeak => '\u{f4f9}',
        Ember => '\u{f423}',
        AmazonPay => '\u{f42c}',
        Joget => '\u{f3b7}',
        TencentWeibo => '\u{f1d5}',
        Artstation => '\u{f77a}',
        Freebsd => '\u{f3a4}',
        Contao => '\u{f26d}',
        GoogleDrive => '\u{f3aa}',
        Vaadin => '\u{f408}',
        Cuttlefish => '\u{f38c}',
        Periscope => '\u{f3da}',
        Searchengin => '\u{f3eb}',
        TheRedYeti => '\u{f69d}',
        Neos => '\u{f612}',
        GooglePlus => '\u{f0d5}',
        FacebookMessenger => '\u{f39f}',
        Openid => '\u{f19b}',
        Viacoin => '\u{f237}',
        Quora => '\u{f2c4}',
        XingSquare => '\u{f169}',
        Pinterest => '\u{f0d2}',
        Autoprefixer => '\u{f41c}',
        AlternateFontAwesome => '\u{f2b4}',
        StripeCreditCard => '\u{f1f5}',
        Strava => '\u{f428}',
        Snapchat => '\u{f2ab}',
        InternetExplorer => '\u{f26b}',
        Invision => '\u{f7b0}',
        GoodreadsG => '\u{f3a9}',
        Opera => '\u{f26a}',
        DiggLogo => '\u{f1a6}',
        Waze => '\u{f83f}',
        Python => '\u{f3e2}',
        YandexInternational => '\u{f414}',
        Rockrms => '\u{f3e9}',
        WeixinWechat => '\u{f1d7}',
        Mendeley => '\u{f7b3}',
        Salesforce => '\u{f83b}',
        Simplybuilt => '\u{f215}',
        RebelAlliance => '\u{f1d0}',
        Angular => '\u{f420}',
        FontAwesomeFlag => '\u{f425}',
        CanadianMapleLeaf => '\u{f785}',
        Elementor => '\u{f430}',
        Centos => '\u{f789}',
        Ravelry => '\u{f2d9}',
        LastFm => '\u{f202}',
        AmazonPayCreditCard => '\u{f42d}',
        FacebookF => '\u{f39e}',
        Dashcube => '\u{f210}',
        Yelp => '\u{f1e9}',
        EnviraGallery => '\u{f299}',
        JoomlaLogo => '\u{f1aa}',
        CriticalRole => '\u{f6c9}',
        AlternateCss3Logo => '\u{f38b}',
        Line => '\u{f3c0}',
        JavascriptJs => '\u{f3b8}',
        Ups => '\u{f7e0}',
        Evernote => '\u{f839}',
        Flipboard => '\u{f44d}',
        Airbnb => '\u{f834}',
        Instagram => '\u{f16d}',
        Goodreads => '\u{f3a8}',
        Confluence => '\u{f78d}',
        RedditLogo => '\u{f1a1}',
        TumblrSquare => '\u{f174}',
        Hips => '\u{f452}',
        VisaCreditCard => '\u{f1f0}',
        Playstation => '\u{f3df}',
        Nutritionix => '\u{f3d6}',
        FonticonsFi => '\u{f280}',
        GlideG => '\u{f2a6}',
        Slideshare => '\u{f1e7}',
        Sketch => '\u{f7c6}',
        Delicious => '\u{f1a5}',
        Laravel => '\u{f3bd}',
        StripeS => '\u{f42a}',
        EdgeBrowser => '\u{f282}',
        Pagelines => '\u{f18c}',
        MaterialDesignForBootstrap => '\u{f8ca}',
        Swift => '\u{f8e1}',
        Superpowers => '\u{f2dd}',
        StackOverflow => '\u{f16c}',
        Buysellads => '\u{f20d}',
        HackerNews => '\u{f1d4}',
        Steam => '\u{f1b6}',
        BloggerB => '\u{f37d}',
        PhoenixSquadron => '\u{f511}',
        Uber => '\u{f402}',
        ItunesNote => '\u{f3b5}',
        Odnoklassniki => '\u{f263}',
        GoogleWallet => '\u{f1ee}',
        Discord => '\u{f392}',
        Ns8 => '\u{f3d5}',
        OptinMonster => '\u{f23c}',
        Speakap => '\u{f3f3}',
        Buffer => '\u{f837}',
        Jenkis => '\u{f3b6}',
        Keybase => '\u{f4f5}',
        Firstdraft => '\u{f3a1}',
        Suse => '\u{f7d6}',
        Resolving => '\u{f3e7}',
        GithubSquare => '\u{f092}',
        WordpressSimple => '\u{f411}',
        Microsoft => '\u{f3ca}',
        Ubuntu => '\u{f7df}',
        Mailchimp => '\u{f59e}',
        Firefox => '\u{f269}',
        Adversal => '\u{f36a}',
        Fedora => '\u{f798}',
        VueJs => '\u{f41f}',
        Apple => '\u{f179}',
        Sourcetree => '\u{f7d3}',
        Foursquare => '\u{f180}',
        Blackberry => '\u{f37b}',
        Qq => '\u{f1d6}',
        Weibo => '\u{f18a}',
        Less => '\u{f41d}',
        Gitlab => '\u{f296}',
        ItchIo => '\u{f83a}',
        Php => '\u{f457}',
        Dochub => '\u{f394}',
        Chrome => '\u{f268}',
        StumbleuponCircle => '\u{f1a3}',
        AcquisitionsIncorporated => '\u{f6af}',
        Megaport => '\u{f5a3}',
        Affiliatetheme => '\u{f36b}',
        IosAppStore => '\u{f370}',
        Servicestack => '\u{f3ec}',
        Mastodon => '\u{f4f6}',
        NodeJsJs => '\u{f3d3}',
        FreeCodeCamp => '\u{f2c5}',
        NodeJs => '\u{f419}',
        WordpressLogo => '\u{f19a}',
        TwitterSquare => '\u{f081}',
        ProductHunt => '\u{f288}',
        Aviato => '\u{f421}',
        Pushed => '\u{f3e1}',
        Mrt => '\u{f3c8}',
        Sellcast => '\u{f2da}',
        Lyft => '\u{f3c3}',
        Ethereum => '\u{f42e}',
        CreativeCommonsSampling => '\u{f4f1}',
        Markdown => '\u{f60f}',
        Napster => '\u{f3d2}',
        Ello => '\u{f5f1}',
        CreativeCommonsShareAlike => '\u{f4ef}',
        Bootstrap => '\u{f836}',
        Fulcrum => '\u{f50b}',
        Windows => '\u{f17a}',
        ShirtsInBulk => '\u{f214}',
        Gulp => '\u{f3ae}',
        Vimeo => '\u{f27d}',
        RocketChat => '\u{f3e8}',
        WizardsOfTheCoast => '\u{f730}',
        Android => '\u{f17b}',
        Sistrix => '\u{f3ee}',
        TradeFederation => '\u{f513}',
        Zhihu => '\u{f63f}',
        Video => '\u{f2a9}',
        Wpbeginner => '\u{f297}',
        Atlassian => '\u{f77b}',
        Ebay => '\u{f4f4}',
        Medium => '\u{f23a}',
        CreativeCommonsShare => '\u{f4f2}',
        Skyatlas => '\u{f216}',
        Safari => '\u{f267}',
        FortAwesome => '\u{f286}',
        Mixcloud => '\u{f289}',
        RProject => '\u{f4f7}',
        Audible => '\u{f373}',
        GetPocket => '\u{f265}',
        OpenSourceInitiative => '\u{f41a}',
        Erlang => '\u{f39d}',
        Bitcoin => '\u{f15a}',
        GitAlt => '\u{f1d3}',
        Dyalog => '\u{f399}',
        AlternateCreativeCommonsPublicDomain => '\u{f4ed}',
        PinterestP => '\u{f231}',
        GoogleLogo => '\u{f1a0}',
        Npm => '\u{f3d4}',
        FacebookSquare => '\u{f082}',
        Jira => '\u{f7b1}',
        StackExchange => '\u{f18d}',
        Hackerrank => '\u{f5f7}',
        Sass => '\u{f41e}',
        PiedPiperHat => '\u{f4e5}',
        Fly => '\u{f417}',
        Css3Logo => '\u{f13c}',
        Deviantart => '\u{f1bd}',
        GgCurrency => '\u{f260}',
        GooglePlusSquare => '\u{f0d4}',
        Html5Logo => '\u{f13b}',
        BRomBelExperteGmbhCoKg => '\u{f37f}',
        RaspberryPi => '\u{f7bb}',
        AlternateGithub => '\u{f113}',
        Leanpub => '\u{f212}',
        Forumbee => '\u{f211}',
        DigitalOcean => '\u{f391}',
        Bitbucket => '\u{f171}',
        SteamSymbol => '\u{f3f6}',
        Twitch => '\u{f1e8}',
        Blogger => '\u{f37c}',
        Spotify => '\u{f1bc}',
        YahooLogo => '\u{f19e}',
        Yandex => '\u{f413}',
        CottonBureau => '\u{f89e}',
        Jsfiddle => '\u{f1cc}',
        Etsy => '\u{f2d7}',
        Phabricator => '\u{f3db}',
        Squarespace => '\u{f5be}',
        RedRiver => '\u{f3e3}',
        ConnectDevelop => '\u{f20e}',
        KickstarterK => '\u{f3bc}',
        Expeditedssl => '\u{f23e}',
        ApplePayCreditCard => '\u{f416}',
        Itunes => '\u{f3b4}',
        Vine => '\u{f1ca}',
        DDBeyond => '\u{f6ca}',
        Bimobject => '\u{f378}',
        Bluetooth => '\u{f294}',
        Earlybirds => '\u{f39a}',
        ApplePay => '\u{f415}',
        SlackHashtag => '\u{f198}',
        Linode => '\u{f2b8}',
        GitSquare => '\u{f1d2}',
        Uniregistry => '\u{f404}',
        AlternateFortAwesome => '\u{f3a3}',
        GgCurrencyCircle => '\u{f261}',
        PennyArcade => '\u{f704}',
        PaypalCreditCard => '\u{f1ed}',
        Researchgate => '\u{f4f8}',
        Tripadvisor => '\u{f262}',
        Themeisle => '\u{f2b2}',
        Skype => '\u{f17e}',
        StickerMule => '\u{f3f7}',
        Sellsy => '\u{f213}',
        Kaggle => '\u{f5fa}',
        Bity => '\u{f37a}',
        Dhl => '\u{f790}',
        FirstOrder => '\u{f2b0}',
        RedditSquare => '\u{f1a2}',
        Weebly => '\u{f5cc}',
        Cloudversify => '\u{f385}',
        Bandcamp => '\u{f2d5}',
        Grunt => '\u{f3ad}',
        Xbox => '\u{f412}',
        AccessibleIcon => '\u{f368}',
        CreativeCommonsRemix => '\u{f4ee}',
        Glide => '\u{f2a5}',
        DribbbleSquare => '\u{f397}',
        Symfony => '\u{f83d}',
        Mix => '\u{f3cb}',
        Bluetooth2 => '\u{f293}',
        Meetup => '\u{f2e0}',
        SpeakerDeck => '\u{f83c}',
        Monero => '\u{f3d0}',
        LastFmSquare => '\u{f203}',
        GooglePlay => '\u{f3ab}',
        Diaspora => '\u{f791}',
        Docker => '\u{f395}',
        CreativeCommonsCc0 => '\u{f4f3}',
        Patreon => '\u{f3d9}',
        JediOrder => '\u{f50e}',
        DeployDog => '\u{f38e}',
        Reacteurope => '\u{f75d}',
        Untappd => '\u{f405}',
        BattleNet => '\u{f835}',
        Gitkraken => '\u{f3a6}',
        Houzz => '\u{f27c}',
        YoutubeSquare => '\u{f431}',
        LinkedinIn => '\u{f0e1}',
        RevIo => '\u{f5b2}',
        Usb => '\u{f287}',
        Accusoft => '\u{f369}',
        Deskpro => '\u{f38f}',
        Replyd => '\u{f3e6}',
        CreativeCommonsAttribution => '\u{f4e7}',
        Centercode => '\u{f380}',
        GalacticEmpire => '\u{f1d1}',
        Nimblr => '\u{f5a8}',
        Page4Corporation => '\u{f3d7}',
        Uikit => '\u{f403}',
        CreativeCommonsNoncommercial => '\u{f4e8}',
        Korvue => '\u{f42f}',
        Hireahelper => '\u{f3b0}',
        Tumblr => '\u{f173}',
        CreativeCommonsNoncommercialYenSign => '\u{f4ea}',
        Soundcloud => '\u{f1be}',
        AngryCreative => '\u{f36e}',
        Yammer => '\u{f840}',
        Fedex => '\u{f797}',
        Linux => '\u{f17c}',
        Intercom => '\u{f7af}',
        VideoSquare => '\u{f2aa}',
        Discourse => '\u{f393}',
        Modx => '\u{f285}',
        Hornbill => '\u{f592}',
        GratipayGittip => '\u{f184}',
        Alipay => '\u{f642}',
        ApperSystemsAb => '\u{f371}',
        Linkedin => '\u{f08c}',
        Amazon => '\u{f270}',
        DiscoverCreditCard => '\u{f1f2}',
        Yarn => '\u{f7e3}',
        Draft2digital => '\u{f396}',
        Vnv => '\u{f40b}',
        Kickstarter => '\u{f3bb}',
        WikipediaW => '\u{f266}',
        VimeoSquare => '\u{f194}',
        CreativeCommonsNoncommercialEuroSign => '\u{f4e9}',
        WolfPackBattalion => '\u{f514}',
        StudioVinari => '\u{f3f8}',
        Cloudsmith => '\u{f384}',
        MastercardCreditCard => '\u{f1f1}',
        BuyNLarge => '\u{f8a6}',
        Vk => '\u{f189}',
        Hooli => '\u{f427}',
        Amilia => '\u{f36d}',
        Gofore => '\u{f3a7}',
        Redhat => '\u{f7bc}',
        OdnoklassnikiSquare => '\u{f264}',
        Gitter => '\u{f426}',
        Dribbble => '\u{f17d}',
        Mandalorian => '\u{f50f}',
        Yoast => '\u{f2b1}',
        PhoenixFramework => '\u{f3dc}',
        Chromecast => '\u{f838}',
        DrupalLogo => '\u{f1a9}',
        Dropbox => '\u{f16b}',
        Medapps => '\u{f3c6}',
        Shopware => '\u{f5b5}',
        Hotjar => '\u{f3b1}',
        Hubspot => '\u{f3b2}',
        ThinkPeaks => '\u{f731}',
        Flickr => '\u{f16e}',
        Whmcs => '\u{f40d}',
        Mizuni => '\u{f3cc}',
        Avianex => '\u{f374}',
        Wpforms => '\u{f298}',
        Magento => '\u{f3c4}',
        AsymmetrikLtd => '\u{f372}',
        Staylinked => '\u{f3f5}',
        Typo3 => '\u{f42b}',
        Behance => '\u{f1b4}',
        WhatSApp => '\u{f232}',
        FantasyFlightGames => '\u{f6dc}',
        FontAwesomeBlackTie => '\u{f27e}',
        CodiePie => '\u{f284}',
        Stackpath => '\u{f842}',
        Xing => '\u{f168}',
        Maxcdn => '\u{f136}',
        Twitter => '\u{f099}',
        _500px => '\u{f26e}',
        Facebook => '\u{f09a}',
        Supple => '\u{f3f9}',
        Imdb => '\u{f2d8}',
        DungeonsDragons => '\u{f38d}',
        WhatSAppSquare => '\u{f40c}',
        CreativeCommons2 => '\u{f4f0}',
        Orcid => '\u{f8d2}',
        Wix => '\u{f5cf}',
        JavascriptJsSquare => '\u{f3b9}',
        React => '\u{f41b}',
        CloudscaleCh => '\u{f383}',
        Trello => '\u{f181}',
        AlternateFirstOrder => '\u{f50a}',
        PinterestSquare => '\u{f0d3}',
        UnitedStatesPostalService => '\u{f7e1}',
        CreativeCommonsPublicDomain => '\u{f4ec}',
        Readme => '\u{f4d5}',
        UsSunnahFoundation => '\u{f407}',
        Github => '\u{f09b}',
        AmericanExpressCreditCard => '\u{f1f3}',
        Scribd => '\u{f28a}',
        Ioxhost => '\u{f208}',
        Keycdn => '\u{f3ba}',
        Schlix => '\u{f3ea}',
        SnapchatSquare => '\u{f2ad}',
        SteamSquare => '\u{f1b7}',
        AppStore => '\u{f36f}',
        GalacticSenate => '\u{f50d}',
        Palfed => '\u{f3d8}',
        Youtube => '\u{f167}',
        Wpressr => '\u{f3e4}',
        Wpexplorer => '\u{f2de}',
        BehanceSquare => '\u{f1b5}',
        Grav => '\u{f2d6}',
        Sith => '\u{f512}',
        JcbCreditCard => '\u{f24b}',
    }
}

impl From<IconBrands> for char {
    fn from(icon: IconBrands) -> Self {
        icon_unicode(icon)
    }
}

impl From<IconBrands> for String {
    fn from(icon: IconBrands) -> Self {
        format!("{}", icon_unicode(icon))
    }
}

impl std::fmt::Display for IconBrands {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", icon_unicode(*self))
    }
}