#[derive(Debug, Clone, Copy, Hash)]
pub enum Icons {
    FileContract ,
    Scroll ,
    Unlink ,
    Tablet ,
    CloudWithAChanceOfMeatball ,
    Building ,
    Map ,
    Jedi ,
    Stamp ,
    AlternateFeather ,
    NeutralFace ,
    EyeSlash ,
    Peace ,
    CaretSquareUp ,
    Equals ,
    SwimmingPool ,
    DrumSteelpan ,
    Copy ,
    Rss ,
    Bars ,
    ListOl ,
    Chair ,
    DotCircle ,
    GrinningFaceWithBigEyes ,
    Dna ,
    PlaneArrival ,
    Save ,
    Binoculars ,
    Language ,
    Italic ,
    ArrowDown ,
    Kaaba ,
    Taxi ,
    FaceWithTearsOfJoy ,
    ArrowLeft ,
    StarHalf ,
    Restroom ,
    Leaf ,
    Subway ,
    CowboyHat ,
    GripVertical ,
    Plane ,
    Tablets ,
    Egg ,
    Stopwatch ,
    MousePointer ,
    SmilingFace ,
    GrinningFaceWithSmilingEyes ,
    MinusCircle ,
    AudioFile ,
    Divide ,
    Blind ,
    HotPepper ,
    VolleyballBall ,
    ChessKing ,
    AlternateHospital ,
    BatteryFull ,
    WindowMaximize ,
    LoudlyCryingFace ,
    StickyNote ,
    AlternateTransgender ,
    VolumeOff ,
    UserGraduate ,
    UserTie ,
    Snowplow ,
    AlternateShareSquare ,
    AlignRight ,
    ThermometerFull ,
    MedicalFile ,
    GlobeWithEuropeShown ,
    BoxOpen ,
    Swimmer ,
    DigitalTachograph ,
    AlternateExchange ,
    Minus ,
    Hashtag ,
    Ship ,
    SortAlphabeticalUp ,
    Bold ,
    Poop ,
    SpellCheck ,
    AngleDown ,
    Umbrella ,
    ChevronCircleRight ,
    Film ,
    UserFriends ,
    PrescriptionBottle ,
    AlternateMedicalFile ,
    AngryFace ,
    PrayingHands ,
    XRay ,
    AlternateCrop ,
    Cocktail ,
    WindowRestore ,
    LessThan ,
    MicrophoneSlash ,
    Brain ,
    Star ,
    At ,
    Battery14Full ,
    AddressCard ,
    Comment ,
    ObjectUngroup ,
    AlternateSortAlphabeticalUp ,
    Filter ,
    BabyCarriage ,
    WinkingFace ,
    FileInvoice ,
    WindowClose ,
    Wheelchair ,
    BalanceScale ,
    StreetView ,
    Thermometer12Full ,
    CommentsDollar ,
    Cogs ,
    PeopleCarry ,
    Hamsa ,
    AlternateStarHalf ,
    MarsDouble ,
    Percent ,
    Tape ,
    BezierCurve ,
    Fill ,
    Dharmachakra ,
    MarsStrokeHorizontal ,
    SmokingBan ,
    UmbrellaBeach ,
    Bed ,
    HandHoldingUsDollar ,
    TableTennis ,
    Helicopter ,
    HandHoldingHeart ,
    VideoFile ,
    Undo ,
    AlternateSortNumericDown ,
    HushedFace ,
    Envelope ,
    FaceWithTongue ,
    Poll ,
    CaretSquareDown ,
    UtensilSpoon ,
    PencilRuler ,
    Battery12Full ,
    ToggleOn ,
    Briefcase ,
    RssSquare ,
    Headset ,
    Train ,
    PauseCircle ,
    FolderOpen ,
    UserEdit ,
    Video ,
    Folder ,
    YinYang ,
    Hryvnia ,
    BatteryEmpty ,
    Flag ,
    MedicalBriefcase ,
    Calculator ,
    Voicemail ,
    QuoteLeft ,
    Gavel ,
    Hands ,
    HandPointingRight ,
    AlternateUnlock ,
    Toilet ,
    MinusSquare ,
    PizzaSlice ,
    GlobeWithAmericasShown ,
    UserSlash ,
    Archive ,
    Sleigh ,
    AlternateArrowCircleDown ,
    Trash ,
    UserCog ,
    SortAmountDown ,
    HospitalSymbol ,
    ExclamationTriangle ,
    Allergies ,
    HourglassEnd ,
    ExcelFile ,
    Genderless ,
    SquareFull ,
    Landmark ,
    ShoppingCartArrowDown ,
    RulerHorizontal ,
    CaretSquareLeft ,
    PointerHand ,
    Tasks ,
    Skull ,
    Robot ,
    Snowflake ,
    FileExport ,
    Outdent ,
    Tags ,
    StarStruck ,
    VenusDouble ,
    Hotel ,
    Camera ,
    Palette ,
    StopCircle ,
    GripLines ,
    Comments ,
    Tty ,
    Vihara ,
    UserNinja ,
    Procedures ,
    Cookie ,
    Slash ,
    AlternateSortAmountUp ,
    ChevronRight ,
    ClosedCaptioning ,
    ThumbsDown ,
    Bacon ,
    AlternateSignIn ,
    BowlingBall ,
    AngleDoubleLeft ,
    Horse ,
    TruckLoading ,
    Strikethrough ,
    StarAndCrescent ,
    HotDog ,
    AssistiveListeningSystems ,
    Male ,
    Forward ,
    Check ,
    Route ,
    ArrowRight ,
    Water ,
    Images ,
    Khanda ,
    Crutch ,
    LayerGroup ,
    WonSign ,
    Compass ,
    TurkishLiraSign ,
    Crosshairs ,
    CodeFile ,
    FillDrip ,
    ThermometerEmpty ,
    CalendarWithDayFocus ,
    Medal ,
    Tractor ,
    ArrowUp ,
    TrashRestore ,
    DiceD20 ,
    BirthdayCake ,
    Asterisk ,
    Poo ,
    AlternateRadiation ,
    BorderAll ,
    ChalkboardTeacher ,
    CloudWithRain ,
    Socks ,
    HelpingHands ,
    Capsules ,
    Heartbeat ,
    FileCsv ,
    PuzzlePiece ,
    CarBattery ,
    Atom ,
    SortNumericDown ,
    MapMarked ,
    SquintingFaceWithTongue ,
    Quran ,
    Burn ,
    StepForward ,
    Clipboard ,
    ChessRook ,
    Sitemap ,
    Book ,
    Igloo ,
    AngleRight ,
    TruckMoving ,
    Newspaper ,
    AlternatePrescriptionBottle ,
    HandPointingLeft ,
    HorizontalEllipsis ,
    EnvelopeOpenText ,
    ObjectGroup ,
    Image ,
    Keyboard ,
    ChessQueen ,
    Percentage ,
    Qrcode ,
    GrinningSquintingFace ,
    Baby ,
    Tint ,
    HandPointingDown ,
    FireExtinguisher ,
    StarOfDavid ,
    BreadSlice ,
    DollarSign ,
    AlternateCloudDownload ,
    BorderNone ,
    Gem ,
    CalendarWithWeekFocus ,
    KissingFaceWithSmilingEyes ,
    CaretUp ,
    WineGlass ,
    ChevronDown ,
    MoneyCheck ,
    SolarPanel ,
    DiceSix ,
    PhoneSquare ,
    AlternateMobile ,
    BusinessTime ,
    TextWidth ,
    AlternateExpandArrows ,
    UserLock ,
    School ,
    ShoePrints ,
    Quidditch ,
    Archway ,
    Info ,
    MoneyBill ,
    CommentSlash ,
    Braille ,
    AlternatePhoneSquare ,
    Cubes ,
    BalanceScaleRightWeighted ,
    Mitten ,
    Cube ,
    History ,
    GlobeWithAfricaShown ,
    AddressBook ,
    FaceWithoutMouth ,
    UserSecret ,
    PaperPlane ,
    GasPump ,
    Trophy ,
    AlternateArrowCircleUp ,
    PlayCircle ,
    Donate ,
    Fax ,
    Meteor ,
    UserTag ,
    University ,
    GreaterThan ,
    LineChart ,
    DiceFour ,
    Seedling ,
    Fish ,
    MedicalBook ,
    Mask ,
    MapSigns ,
    ExclamationCircle ,
    Tools ,
    ImageFile ,
    ChevronCircleDown ,
    Paragraph ,
    LaptopCode ,
    DizzyFace ,
    PiggyBank ,
    LaughingWinkingFace ,
    Skating ,
    Terminal ,
    BookOpen ,
    Ankh ,
    UserMinus ,
    Sort ,
    AlternateMoneyBill ,
    MartiniGlass ,
    CloudWithSunAndRain ,
    TextHeight ,
    CalendarTimes ,
    PenSquare ,
    Award ,
    UserPlus ,
    CloudWithSun ,
    Coins ,
    AlternateTachometer ,
    SkullCrossbones ,
    BorderStyle ,
    AlternateLevelDown ,
    Barcode ,
    ArrowCircleRight ,
    Tag ,
    AlternateArrowsHorizontal ,
    ClipboardWithCheck ,
    RollingOnTheFloorLaughing ,
    Sms ,
    RecordVinyl ,
    City ,
    AngleLeft ,
    Trademark ,
    TimesCircle ,
    Mountain ,
    ShoppingCart ,
    MarsStrokeVertical ,
    AlternateUserSlash ,
    GripHorizontal ,
    Ad ,
    Heading ,
    Walking ,
    Search ,
    DoubleCheck ,
    SearchDollar ,
    Box ,
    VoteYea ,
    SuitcaseRolling ,
    FolderMinus ,
    CalendarPlus ,
    Bug ,
    Democrat ,
    MapPin ,
    CryingFace ,
    FileUpload ,
    Bus ,
    GraduationCap ,
    FastBackward,
    SortAmountUp,
    ListUl,
    Om,
    Shower,
    Icons,
    AlternateUser,
    Music,
    Database,
    Cut,
    AlternateSortNumericUp,
    AlternateRedo,
    DoorClosed,
    Reply,
    Thermometer14Full,
    ArrowCircleLeft,
    Haykal,
    Home,
    ChessBoard,
    CaretLeft,
    InfoCircle,
    Warehouse,
    FruitApple,
    Motorcycle,
    PowerpointFile,
    ChargingStation,
    HockeyPuck,
    ShoppingBasket,
    Lock,
    AlignCenter,
    NotEqual,
    Hdd,
    Exclamation,
    Chess,
    PoundSign,
    Hourglass,
    AlternateFire,
    Laptop,
    Ring,
    DiceFive,
    DiceOne,
    Cannabis,
    CreditCard,
    Tooth,
    UserShield,
    Subscript,
    BookReader,
    Pager,
    Industry,
    GlobeWithAsiaShown,
    DumpsterFire,
    RulerVertical,
    Underline,
    Wind,
    BellSlash,
    Lemon,
    PhotoVideo,
    QuoteRight,
    AlternateStore,
    ReplyAll,
    AlternateExternalLinkSquare,
    AlignLeft,
    Snowboarding,
    PenFancy,
    AlternateArrowsVertical,
    Th,
    AlternateSortAmountDown,
    PooStorm,
    Pause,
    CowboyHatSide,
    PlaceOfWorship,
    Gopuram,
    Ethernet,
    FighterJet,
    AlternateExternalLink,
    Snowman,
    DollyFlatbed,
    AlternateGrinningFace,
    WizardSHat,
    PenNib,
    Dove,
    SearchLocation,
    Cat,
    ArrowCircleDown,
    AlternateArrowCircleRight,
    EuroSign,
    Icicles,
    Random,
    VenusMars,
    VerticalEllipsis,
    ArchiveFile,
    AlternateTicket,
    AlternateCar,
    AlternateLongArrowLeft,
    LizardHand,
    Magnet,
    AlternateLongArrowUp,
    Crow,
    Marker,
    YenSign,
    BaseballBall,
    BalanceScaleLeftWeighted,
    Pray,
    Redo,
    Eraser,
    Utensils,
    VideoSlash,
    Eject,
    Thermometer34Full,
    Thumbtack,
    StarOfLife,
    BookOfTheDead,
    CashRegister,
    Fire,
    Ghost,
    ThumbsUp,
    HorseHead,
    Anchor,
    Smog,
    AlternateCloudUpload,
    Hospital,
    ThLarge,
    VolumeUp,
    RubleSign,
    KissingFace,
    FaceBlowingAKiss,
    BarChart,
    Boxes,
    Play,
    Pallet,
    AlternateShield,
    Wrench,
    Ribbon,
    CommentDollar,
    Rainbow,
    DiceD6,
    Link,
    Deaf,
    Globe,
    Torah,
    SkiingNordic,
    HeartBroken,
    Dungeon,
    Heart,
    MortarPestle,
    Shapes,
    ChevronUp,
    FootballBall,
    Guitar,
    TrafficLight,
    AlignJustify,
    Fingerprint,
    Dog,
    AlternateComment,
    Users,
    Drum,
    PollH,
    PlusSquare,
    AlternateHeadphones,
    AlternateList,
    Microchip,
    SmilingFaceWithHeartEyes,
    Paw,
    AlternateArrowCircleLeft,
    TruckMonster,
    Hamburger,
    Radiation,
    Mars,
    AngleDoubleRight,
    ConciergeBell,
    Satellite,
    SearchPlus,
    Stethoscope,
    Table,
    Rocket,
    TiredFace,
    PeaceHand,
    Times,
    Bible,
    Unlock,
    Swatchbook,
    Carrot,
    AlternateSignOut,
    HighTemperature,
    Biking,
    StepBackward,
    Upload,
    Syringe,
    AlternateShare,
    Otter,
    CalendarMinus,
    Pills,
    GlassWhiskey,
    Lightbulb,
    AlternateArrows,
    Key,
    CandyCane,
    Adjust,
    CloudWithHeavyShowers,
    WavyMoneyBill,
    Glasses,
    Memory,
    Download,
    Car,
    Synagogue,
    GripLinesVertical,
    HollyBerry,
    MailBulk,
    Diagnoses,
    CheckSquare,
    Running,
    Blog,
    User,
    Retweet,
    CodeBranch,
    SpockHand,
    Screwdriver,
    Dragon,
    ToiletPaper,
    Wifi,
    ThList,
    FunnelDollar,
    MarsStroke,
    Joint,
    AngleUp,
    AreaChart,
    LowTemperature,
    PieChart,
    FolderPlus,
    Ban,
    Menorah,
    AlternateLongArrowDown,
    HardHat,
    CarSide,
    Female,
    BlenderPhone,
    Cloud,
    FileDownload,
    Splotch,
    Tenge,
    Server,
    HotTub,
    LowVision,
    AlternateMedicalChat,
    Desktop,
    UserAstronaut,
    IdentificationCard,
    Paperclip,
    Sync,
    PaintBrush,
    Gifts,
    Mercury,
    CalendarCheck,
    BandAid,
    Moon,
    Ruler,
    Feather,
    Microscope,
    AirFreshener,
    ChessPawn,
    ShuttleVan,
    Calendar,
    File,
    SimCard,
    ArrowCircleUp,
    Venus,
    Gamepad,
    ParachuteBox,
    Suitcase,
    PaintRoller,
    MugHot,
    Indent,
    PhoneVolume,
    AlternateCompressArrows,
    Clock,
    Magic,
    Spinner,
    ShekelSign,
    Sun,
    Share,
    AmericanSignLanguageInterpreting,
    Cross,
    SortAlphabeticalDown,
    HandPointingUp,
    Flask,
    UserCircle,
    Vials,
    JournalOfTheWhills,
    Plus,
    AlternateMapMarker,
    Bong,
    SprayCan,
    EnvelopeOpen,
    Store,
    CompactDisc,
    UniversalAccess,
    Print,
    Wallet,
    Compress,
    HandWithMiddleFingerRaised,
    AlternateUndo,
    Question,
    AlternativeTrashRestore,
    IndianRupeeSign,
    AlternateSortAlphabeticalDown,
    Prescription,
    CaretRight,
    Road,
    AlternatePencil,
    GlassCheers,
    Vial,
    AlternateMicrophone,
    AlternateMapMarked,
    Nurse,
    Pen,
    Edit,
    CaretDown,
    ChessKnight,
    AlternatePhone,
    BasketballBall,
    FilePrescription,
    CardboardVr,
    Circle,
    HorizontalSliders,
    AlternateMoneyCheck,
    Tram,
    CloudWithMoonAndRain,
    WordFile,
    Bullseye,
    Tree,
    LessThanEqualTo,
    Chalkboard,
    ToggleOff,
    Signal,
    CircleNotched,
    Hippo,
    EnvelopeSquare,
    FileSignature,
    AlternateFile,
    DiceThree,
    FlushedFace,
    Dumbbell,
    Transgender,
    LifeRing,
    SquareWave,
    AlternateWavyMoneyBill,
    AudioDescription,
    Frog,
    CaretSquareRight,
    RemoveFormat,
    Bicycle,
    PowerOff,
    TeethOpen,
    PlaneDeparture,
    Inbox,
    Parking,
    PersonEnteringBooth,
    RulerCombined,
    WineBottle,
    Backspace,
    HourglassStart,
    BeamingFaceWithSmilingEyes,
    Pastafarianism,
    Crop,
    DrumstickWithBiteTakenOut,
    Republican,
    Bomb,
    WiredNetwork,
    Crown,
    UsersCog,
    QuestionCircle,
    RemoveUser,
    TintSlash,
    Eye,
    Hammer,
    PdfFile,
    Signature,
    FrowningFace,
    FlagCheckered,
    UserCheck,
    Bath,
    WindowMinimize,
    Podcast,
    Microphone,
    TheaterMasks,
    Spa,
    UserInjured,
    RegisteredTrademark,
    Blender,
    SatelliteDish,
    CommentDots,
    WinkingFaceWithTongue,
    Cog,
    Futbol,
    SearchMinus,
    DamagedHouse,
    IceCream,
    RetroCamera,
    ChevronCircleLeft,
    EyeDropper,
    TShirt,
    DrawPolygon,
    Church,
    Dice,
    Thermometer,
    Bone,
    AlternateMicrophoneSlash,
    MedicalNotes,
    Clone,
    ShareSquare,
    IBeamCursor,
    LaptopMedical,
    HourglassHalf,
    Broom,
    ChessBishop,
    SdCard,
    GreaterThanEqualTo,
    Brush,
    Gift,
    Toolbox,
    Code,
    Mouse,
    VectorSquare,
    AddToShoppingCart,
    PhoneSlash,
    ShippingFast,
    BroadcastTower,
    Copyright,
    Plug,
    SpaceShuttle,
    Bell,
    Teeth,
    Mosque,
    Monument,
    AlternatePen,
    Doctor,
    SortNumericUp,
    AngleDoubleDown,
    FileImport,
    Stroopwafel,
    PaperHand,
    DoorOpen,
    Dumpster,
    PlusCircle,
    ScissorsHand,
    FileInvoiceWithUsDollar,
    LightningBolt,
    Bookmark,
    Atlas,
    Stop,
    AlternateWineGlas,
    Battery34Full,
    GrimacingFace,
    HandHolding,
    Weight,
    AlternateLevelUp,
    Television,
    Portrait,
    ClipboardList,
    Campground,
    Ambulance,
    Passport,
    Fan,
    CheckCircle,
    LocationArrow,
    AngleDoubleUp,
    Dolly,
    GolfBall,
    DraftingCompass,
    Handshake,
    KiwiBird,
    ShoppingBag,
    Font,
    Bullhorn,
    Sign,
    ProjectDiagram,
    ChevronLeft,
    Directions,
    AlternateSquareRoot,
    SignLanguage,
    BusAlt,
    Child,
    Couch,
    CarCrash,
    DiceTwo,
    Receipt,
    ChevronCircleUp,
    Phone,
    Recycle,
    Hiking,
    GrinningFaceWithSweat,
    Spider,
    Beer,
    IdentificationBadge,
    Biohazard,
    VolumeDown,
    UnitedStatesOfAmericaFlag,
    Cheese,
    Columns,
    AlternateIdentificationCard,
    TruckSide,
    RaisedFist,
    Hanukiah,
    Smoking,
    RockHand,
    HangingWeight,
    CookieBite,
    Stream,
    Skiing,
    ToriiGate,
    FaceWithRollingEyes,
    Coffee,
    AlternateLongArrowRight,
    UserClock,
    OilCan,
    CloudWithMoon,
    Superscript,
    AlternateTrash,
    Expand,
    Infinity,
}


fn icon_unicode(icon: Icons) -> char {
    use self::Icons::*;
    match icon {
        FileContract => '\u{f56c}',
        Scroll => '\u{f70e}',
        Unlink => '\u{f127}',
        Tablet => '\u{f10a}',
        CloudWithAChanceOfMeatball => '\u{f73b}',
        Building => '\u{f1ad}',
        Map => '\u{f279}',
        Jedi => '\u{f669}',
        Stamp => '\u{f5bf}',
        AlternateFeather => '\u{f56b}',
        NeutralFace => '\u{f11a}',
        EyeSlash => '\u{f070}',
        Peace => '\u{f67c}',
        CaretSquareUp => '\u{f151}',
        Equals => '\u{f52c}',
        SwimmingPool => '\u{f5c5}',
        DrumSteelpan => '\u{f56a}',
        Copy => '\u{f0c5}',
        Rss => '\u{f09e}',
        Bars => '\u{f0c9}',
        ListOl => '\u{f0cb}',
        Chair => '\u{f6c0}',
        DotCircle => '\u{f192}',
        GrinningFaceWithBigEyes => '\u{f580}',
        Dna => '\u{f471}',
        PlaneArrival => '\u{f5af}',
        Save => '\u{f0c7}',
        Binoculars => '\u{f1e5}',
        Language => '\u{f1ab}',
        Italic => '\u{f033}',
        ArrowDown => '\u{f063}',
        Kaaba => '\u{f66b}',
        Taxi => '\u{f1ba}',
        FaceWithTearsOfJoy => '\u{f588}',
        ArrowLeft => '\u{f060}',
        StarHalf => '\u{f089}',
        Restroom => '\u{f7bd}',
        Leaf => '\u{f06c}',
        Subway => '\u{f239}',
        CowboyHat => '\u{f8c0}',
        GripVertical => '\u{f58e}',
        Plane => '\u{f072}',
        Tablets => '\u{f490}',
        Egg => '\u{f7fb}',
        Stopwatch => '\u{f2f2}',
        MousePointer => '\u{f245}',
        SmilingFace => '\u{f118}',
        GrinningFaceWithSmilingEyes => '\u{f582}',
        MinusCircle => '\u{f056}',
        AudioFile => '\u{f1c7}',
        Divide => '\u{f529}',
        Blind => '\u{f29d}',
        HotPepper => '\u{f816}',
        VolleyballBall => '\u{f45f}',
        ChessKing => '\u{f43f}',
        AlternateHospital => '\u{f47d}',
        BatteryFull => '\u{f240}',
        WindowMaximize => '\u{f2d0}',
        LoudlyCryingFace => '\u{f5b4}',
        StickyNote => '\u{f249}',
        AlternateTransgender => '\u{f225}',
        VolumeOff => '\u{f026}',
        UserGraduate => '\u{f501}',
        UserTie => '\u{f508}',
        Snowplow => '\u{f7d2}',
        AlternateShareSquare => '\u{f1e1}',
        AlignRight => '\u{f038}',
        ThermometerFull => '\u{f2c7}',
        MedicalFile => '\u{f477}',
        GlobeWithEuropeShown => '\u{f7a2}',
        BoxOpen => '\u{f49e}',
        Swimmer => '\u{f5c4}',
        DigitalTachograph => '\u{f566}',
        AlternateExchange => '\u{f362}',
        Minus => '\u{f068}',
        Hashtag => '\u{f292}',
        Ship => '\u{f21a}',
        SortAlphabeticalUp => '\u{f15e}',
        Bold => '\u{f032}',
        Poop => '\u{f619}',
        SpellCheck => '\u{f891}',
        AngleDown => '\u{f107}',
        Umbrella => '\u{f0e9}',
        ChevronCircleRight => '\u{f138}',
        Film => '\u{f008}',
        UserFriends => '\u{f500}',
        PrescriptionBottle => '\u{f485}',
        AlternateMedicalFile => '\u{f478}',
        AngryFace => '\u{f556}',
        PrayingHands => '\u{f684}',
        XRay => '\u{f497}',
        AlternateCrop => '\u{f565}',
        Cocktail => '\u{f561}',
        WindowRestore => '\u{f2d2}',
        LessThan => '\u{f536}',
        MicrophoneSlash => '\u{f131}',
        Brain => '\u{f5dc}',
        Star => '\u{f005}',
        At => '\u{f1fa}',
        Battery14Full => '\u{f243}',
        AddressCard => '\u{f2bb}',
        Comment => '\u{f075}',
        ObjectUngroup => '\u{f248}',
        AlternateSortAlphabeticalUp => '\u{f882}',
        Filter => '\u{f0b0}',
        BabyCarriage => '\u{f77d}',
        WinkingFace => '\u{f4da}',
        FileInvoice => '\u{f570}',
        WindowClose => '\u{f410}',
        Wheelchair => '\u{f193}',
        BalanceScale => '\u{f24e}',
        StreetView => '\u{f21d}',
        Thermometer12Full => '\u{f2c9}',
        CommentsDollar => '\u{f653}',
        Cogs => '\u{f085}',
        PeopleCarry => '\u{f4ce}',
        Hamsa => '\u{f665}',
        AlternateStarHalf => '\u{f5c0}',
        MarsDouble => '\u{f227}',
        Percent => '\u{f295}',
        Tape => '\u{f4db}',
        BezierCurve => '\u{f55b}',
        Fill => '\u{f575}',
        Dharmachakra => '\u{f655}',
        MarsStrokeHorizontal => '\u{f22b}',
        SmokingBan => '\u{f54d}',
        UmbrellaBeach => '\u{f5ca}',
        Bed => '\u{f236}',
        HandHoldingUsDollar => '\u{f4c0}',
        TableTennis => '\u{f45d}',
        Helicopter => '\u{f533}',
        HandHoldingHeart => '\u{f4be}',
        VideoFile => '\u{f1c8}',
        Undo => '\u{f0e2}',
        AlternateSortNumericDown => '\u{f886}',
        HushedFace => '\u{f57a}',
        Envelope => '\u{f0e0}',
        FaceWithTongue => '\u{f589}',
        Poll => '\u{f681}',
        CaretSquareDown => '\u{f150}',
        UtensilSpoon => '\u{f2e5}',
        PencilRuler => '\u{f5ae}',
        Battery12Full => '\u{f242}',
        ToggleOn => '\u{f205}',
        Briefcase => '\u{f0b1}',
        RssSquare => '\u{f143}',
        Headset => '\u{f590}',
        Train => '\u{f238}',
        PauseCircle => '\u{f28b}',
        FolderOpen => '\u{f07c}',
        UserEdit => '\u{f4ff}',
        Video => '\u{f03d}',
        Folder => '\u{f07b}',
        YinYang => '\u{f6ad}',
        Hryvnia => '\u{f6f2}',
        BatteryEmpty => '\u{f244}',
        Flag => '\u{f024}',
        MedicalBriefcase => '\u{f0fa}',
        Calculator => '\u{f1ec}',
        Voicemail => '\u{f897}',
        QuoteLeft => '\u{f10d}',
        Gavel => '\u{f0e3}',
        Hands => '\u{f4c2}',
        HandPointingRight => '\u{f0a4}',
        AlternateUnlock => '\u{f13e}',
        Toilet => '\u{f7d8}',
        MinusSquare => '\u{f146}',
        PizzaSlice => '\u{f818}',
        GlobeWithAmericasShown => '\u{f57d}',
        UserSlash => '\u{f506}',
        Archive => '\u{f187}',
        Sleigh => '\u{f7cc}',
        AlternateArrowCircleDown => '\u{f358}',
        Trash => '\u{f1f8}',
        UserCog => '\u{f4fe}',
        SortAmountDown => '\u{f160}',
        HospitalSymbol => '\u{f0fd}',
        ExclamationTriangle => '\u{f071}',
        Allergies => '\u{f461}',
        HourglassEnd => '\u{f253}',
        ExcelFile => '\u{f1c3}',
        Genderless => '\u{f22c}',
        SquareFull => '\u{f0c8}',
        Landmark => '\u{f66f}',
        ShoppingCartArrowDown => '\u{f218}',
        RulerHorizontal => '\u{f547}',
        CaretSquareLeft => '\u{f191}',
        PointerHand => '\u{f25a}',
        Tasks => '\u{f0ae}',
        Skull => '\u{f54c}',
        Robot => '\u{f544}',
        Snowflake => '\u{f2dc}',
        FileExport => '\u{f56e}',
        Outdent => '\u{f03b}',
        Tags => '\u{f02c}',
        StarStruck => '\u{f587}',
        VenusDouble => '\u{f226}',
        Hotel => '\u{f594}',
        Camera => '\u{f030}',
        Palette => '\u{f53f}',
        StopCircle => '\u{f28d}',
        GripLines => '\u{f7a4}',
        Comments => '\u{f086}',
        Tty => '\u{f1e4}',
        Vihara => '\u{f6a7}',
        UserNinja => '\u{f504}',
        Procedures => '\u{f487}',
        Cookie => '\u{f563}',
        Slash => '\u{f715}',
        AlternateSortAmountUp => '\u{f885}',
        ChevronRight => '\u{f054}',
        ClosedCaptioning => '\u{f20a}',
        ThumbsDown => '\u{f165}',
        Bacon => '\u{f7e5}',
        AlternateSignIn => '\u{f2f6}',
        BowlingBall => '\u{f436}',
        AngleDoubleLeft => '\u{f100}',
        Horse => '\u{f6f0}',
        TruckLoading => '\u{f4de}',
        Strikethrough => '\u{f0cc}',
        StarAndCrescent => '\u{f699}',
        HotDog => '\u{f80f}',
        AssistiveListeningSystems => '\u{f2a2}',
        Male => '\u{f183}',
        Forward => '\u{f04e}',
        Check => '\u{f00c}',
        Route => '\u{f4d7}',
        ArrowRight => '\u{f061}',
        Water => '\u{f773}',
        Images => '\u{f302}',
        Khanda => '\u{f66d}',
        Crutch => '\u{f7f7}',
        LayerGroup => '\u{f5fd}',
        WonSign => '\u{f159}',
        Compass => '\u{f14e}',
        TurkishLiraSign => '\u{f195}',
        Crosshairs => '\u{f05b}',
        CodeFile => '\u{f1c9}',
        FillDrip => '\u{f576}',
        ThermometerEmpty => '\u{f2cb}',
        CalendarWithDayFocus => '\u{f783}',
        Medal => '\u{f5a2}',
        Tractor => '\u{f722}',
        ArrowUp => '\u{f062}',
        TrashRestore => '\u{f829}',
        DiceD20 => '\u{f6cf}',
        BirthdayCake => '\u{f1fd}',
        Asterisk => '\u{f069}',
        Poo => '\u{f2fe}',
        AlternateRadiation => '\u{f7ba}',
        BorderAll => '\u{f84c}',
        ChalkboardTeacher => '\u{f51c}',
        CloudWithRain => '\u{f73d}',
        Socks => '\u{f696}',
        HelpingHands => '\u{f4c4}',
        Capsules => '\u{f46b}',
        Heartbeat => '\u{f21e}',
        FileCsv => '\u{f6dd}',
        PuzzlePiece => '\u{f12e}',
        CarBattery => '\u{f5df}',
        Atom => '\u{f5d2}',
        SortNumericDown => '\u{f162}',
        MapMarked => '\u{f59f}',
        SquintingFaceWithTongue => '\u{f58a}',
        Quran => '\u{f687}',
        Burn => '\u{f46a}',
        StepForward => '\u{f051}',
        Clipboard => '\u{f0ea}',
        ChessRook => '\u{f447}',
        Sitemap => '\u{f0e8}',
        Book => '\u{f02d}',
        Igloo => '\u{f7ae}',
        AngleRight => '\u{f105}',
        TruckMoving => '\u{f0d1}',
        Newspaper => '\u{f1ea}',
        AlternatePrescriptionBottle => '\u{f486}',
        HandPointingLeft => '\u{f0a5}',
        HorizontalEllipsis => '\u{f141}',
        EnvelopeOpenText => '\u{f658}',
        ObjectGroup => '\u{f247}',
        Image => '\u{f03e}',
        Keyboard => '\u{f11c}',
        ChessQueen => '\u{f445}',
        Percentage => '\u{f541}',
        Qrcode => '\u{f029}',
        GrinningSquintingFace => '\u{f585}',
        Baby => '\u{f77c}',
        Tint => '\u{f043}',
        HandPointingDown => '\u{f0a7}',
        FireExtinguisher => '\u{f134}',
        StarOfDavid => '\u{f69a}',
        BreadSlice => '\u{f7ec}',
        DollarSign => '\u{f155}',
        AlternateCloudDownload => '\u{f381}',
        BorderNone => '\u{f850}',
        Gem => '\u{f3a5}',
        CalendarWithWeekFocus => '\u{f784}',
        KissingFaceWithSmilingEyes => '\u{f597}',
        CaretUp => '\u{f0d8}',
        WineGlass => '\u{f4e3}',
        ChevronDown => '\u{f078}',
        MoneyCheck => '\u{f53c}',
        SolarPanel => '\u{f5ba}',
        DiceSix => '\u{f526}',
        PhoneSquare => '\u{f098}',
        AlternateMobile => '\u{f10b}',
        BusinessTime => '\u{f64a}',
        TextWidth => '\u{f035}',
        AlternateExpandArrows => '\u{f31e}',
        UserLock => '\u{f502}',
        School => '\u{f549}',
        ShoePrints => '\u{f54b}',
        Quidditch => '\u{f458}',
        Archway => '\u{f557}',
        Info => '\u{f129}',
        MoneyBill => '\u{f0d6}',
        CommentSlash => '\u{f4b3}',
        Braille => '\u{f2a1}',
        AlternatePhoneSquare => '\u{f87b}',
        Cubes => '\u{f1b3}',
        BalanceScaleRightWeighted => '\u{f516}',
        Mitten => '\u{f7b5}',
        Cube => '\u{f1b2}',
        History => '\u{f1da}',
        GlobeWithAfricaShown => '\u{f57c}',
        AddressBook => '\u{f2b9}',
        FaceWithoutMouth => '\u{f5a4}',
        UserSecret => '\u{f21b}',
        PaperPlane => '\u{f1d8}',
        GasPump => '\u{f52f}',
        Trophy => '\u{f091}',
        AlternateArrowCircleUp => '\u{f35b}',
        PlayCircle => '\u{f144}',
        Donate => '\u{f4b9}',
        Fax => '\u{f1ac}',
        Meteor => '\u{f753}',
        UserTag => '\u{f507}',
        University => '\u{f19c}',
        GreaterThan => '\u{f531}',
        LineChart => '\u{f201}',
        DiceFour => '\u{f524}',
        Seedling => '\u{f4d8}',
        Fish => '\u{f578}',
        MedicalBook => '\u{f7e6}',
        Mask => '\u{f6fa}',
        MapSigns => '\u{f277}',
        ExclamationCircle => '\u{f06a}',
        Tools => '\u{f7d9}',
        ImageFile => '\u{f1c5}',
        ChevronCircleDown => '\u{f13a}',
        Paragraph => '\u{f1dd}',
        LaptopCode => '\u{f5fc}',
        DizzyFace => '\u{f567}',
        PiggyBank => '\u{f4d3}',
        LaughingWinkingFace => '\u{f59c}',
        Skating => '\u{f7c5}',
        Terminal => '\u{f120}',
        BookOpen => '\u{f518}',
        Ankh => '\u{f644}',
        UserMinus => '\u{f503}',
        Sort => '\u{f0dc}',
        AlternateMoneyBill => '\u{f3d1}',
        MartiniGlass => '\u{f000}',
        CloudWithSunAndRain => '\u{f743}',
        TextHeight => '\u{f034}',
        CalendarTimes => '\u{f273}',
        PenSquare => '\u{f14b}',
        Award => '\u{f0a3}',
        UserPlus => '\u{f234}',
        CloudWithSun => '\u{f6c4}',
        Coins => '\u{f51e}',
        AlternateTachometer => '\u{f3fd}',
        SkullCrossbones => '\u{f714}',
        BorderStyle => '\u{f853}',
        AlternateLevelDown => '\u{f3be}',
        Barcode => '\u{f02a}',
        ArrowCircleRight => '\u{f0a9}',
        Tag => '\u{f02b}',
        AlternateArrowsHorizontal => '\u{f337}',
        ClipboardWithCheck => '\u{f46c}',
        RollingOnTheFloorLaughing => '\u{f586}',
        Sms => '\u{f7cd}',
        RecordVinyl => '\u{f8d9}',
        City => '\u{f64f}',
        AngleLeft => '\u{f104}',
        Trademark => '\u{f25c}',
        TimesCircle => '\u{f057}',
        Mountain => '\u{f6fc}',
        ShoppingCart => '\u{f07a}',
        MarsStrokeVertical => '\u{f22a}',
        AlternateUserSlash => '\u{f4fa}',
        GripHorizontal => '\u{f58d}',
        Ad => '\u{f641}',
        Heading => '\u{f1dc}',
        Walking => '\u{f554}',
        Search => '\u{f002}',
        DoubleCheck => '\u{f560}',
        SearchDollar => '\u{f688}',
        Box => '\u{f466}',
        VoteYea => '\u{f772}',
        SuitcaseRolling => '\u{f5c1}',
        FolderMinus => '\u{f65d}',
        CalendarPlus => '\u{f271}',
        Bug => '\u{f188}',
        Democrat => '\u{f747}',
        MapPin => '\u{f276}',
        CryingFace => '\u{f5b3}',
        FileUpload => '\u{f574}',
        Bus => '\u{f207}',
        GraduationCap => '\u{f19d}',
        FastBackward => '\u{f049}',
        SortAmountUp => '\u{f161}',
        ListUl => '\u{f03a}',
        Om => '\u{f679}',
        Shower => '\u{f2cc}',
        Icons => '\u{f86d}',
        AlternateUser => '\u{f406}',
        Music => '\u{f001}',
        Database => '\u{f1c0}',
        Cut => '\u{f0c4}',
        AlternateSortNumericUp => '\u{f887}',
        AlternateRedo => '\u{f2f9}',
        DoorClosed => '\u{f52a}',
        Reply => '\u{f3e5}',
        Thermometer14Full => '\u{f2ca}',
        ArrowCircleLeft => '\u{f0a8}',
        Haykal => '\u{f666}',
        Home => '\u{f015}',
        ChessBoard => '\u{f43c}',
        CaretLeft => '\u{f0d9}',
        InfoCircle => '\u{f05a}',
        Warehouse => '\u{f494}',
        FruitApple => '\u{f5d1}',
        Motorcycle => '\u{f21c}',
        PowerpointFile => '\u{f1c4}',
        ChargingStation => '\u{f5e7}',
        HockeyPuck => '\u{f453}',
        ShoppingBasket => '\u{f291}',
        Lock => '\u{f023}',
        AlignCenter => '\u{f037}',
        NotEqual => '\u{f53e}',
        Hdd => '\u{f0a0}',
        Exclamation => '\u{f12a}',
        Chess => '\u{f439}',
        PoundSign => '\u{f154}',
        Hourglass => '\u{f254}',
        AlternateFire => '\u{f7e4}',
        Laptop => '\u{f109}',
        Ring => '\u{f70b}',
        DiceFive => '\u{f523}',
        DiceOne => '\u{f525}',
        Cannabis => '\u{f55f}',
        CreditCard => '\u{f09d}',
        Tooth => '\u{f5c9}',
        UserShield => '\u{f505}',
        Subscript => '\u{f12c}',
        BookReader => '\u{f5da}',
        Pager => '\u{f815}',
        Industry => '\u{f275}',
        GlobeWithAsiaShown => '\u{f57e}',
        DumpsterFire => '\u{f794}',
        RulerVertical => '\u{f548}',
        Underline => '\u{f0cd}',
        Wind => '\u{f72e}',
        BellSlash => '\u{f1f6}',
        Lemon => '\u{f094}',
        PhotoVideo => '\u{f87c}',
        QuoteRight => '\u{f10e}',
        AlternateStore => '\u{f54f}',
        ReplyAll => '\u{f122}',
        AlternateExternalLinkSquare => '\u{f360}',
        AlignLeft => '\u{f036}',
        Snowboarding => '\u{f7ce}',
        PenFancy => '\u{f5ac}',
        AlternateArrowsVertical => '\u{f338}',
        Th => '\u{f00a}',
        AlternateSortAmountDown => '\u{f884}',
        PooStorm => '\u{f75a}',
        Pause => '\u{f04c}',
        CowboyHatSide => '\u{f8c1}',
        PlaceOfWorship => '\u{f67f}',
        Gopuram => '\u{f664}',
        Ethernet => '\u{f796}',
        FighterJet => '\u{f0fb}',
        AlternateExternalLink => '\u{f35d}',
        Snowman => '\u{f7d0}',
        DollyFlatbed => '\u{f474}',
        AlternateGrinningFace => '\u{f581}',
        WizardSHat => '\u{f6e8}',
        PenNib => '\u{f5ad}',
        Dove => '\u{f4ba}',
        SearchLocation => '\u{f689}',
        Cat => '\u{f6be}',
        ArrowCircleDown => '\u{f0ab}',
        AlternateArrowCircleRight => '\u{f35a}',
        EuroSign => '\u{f153}',
        Icicles => '\u{f7ad}',
        Random => '\u{f074}',
        VenusMars => '\u{f228}',
        VerticalEllipsis => '\u{f142}',
        ArchiveFile => '\u{f1c6}',
        AlternateTicket => '\u{f3ff}',
        AlternateCar => '\u{f5de}',
        AlternateLongArrowLeft => '\u{f30a}',
        LizardHand => '\u{f258}',
        Magnet => '\u{f076}',
        AlternateLongArrowUp => '\u{f30c}',
        Crow => '\u{f520}',
        Marker => '\u{f591}',
        YenSign => '\u{f157}',
        BaseballBall => '\u{f433}',
        BalanceScaleLeftWeighted => '\u{f515}',
        Pray => '\u{f683}',
        Redo => '\u{f01e}',
        Eraser => '\u{f12d}',
        Utensils => '\u{f2e7}',
        VideoSlash => '\u{f4e2}',
        Eject => '\u{f052}',
        Thermometer34Full => '\u{f2c8}',
        Thumbtack => '\u{f08d}',
        StarOfLife => '\u{f621}',
        BookOfTheDead => '\u{f6b7}',
        CashRegister => '\u{f788}',
        Fire => '\u{f06d}',
        Ghost => '\u{f6e2}',
        ThumbsUp => '\u{f164}',
        HorseHead => '\u{f7ab}',
        Anchor => '\u{f13d}',
        Smog => '\u{f75f}',
        AlternateCloudUpload => '\u{f382}',
        Hospital => '\u{f0f8}',
        ThLarge => '\u{f009}',
        VolumeUp => '\u{f028}',
        RubleSign => '\u{f158}',
        KissingFace => '\u{f596}',
        FaceBlowingAKiss => '\u{f598}',
        BarChart => '\u{f080}',
        Boxes => '\u{f468}',
        Play => '\u{f04b}',
        Pallet => '\u{f482}',
        AlternateShield => '\u{f3ed}',
        Wrench => '\u{f0ad}',
        Ribbon => '\u{f4d6}',
        CommentDollar => '\u{f651}',
        Rainbow => '\u{f75b}',
        DiceD6 => '\u{f6d1}',
        Link => '\u{f0c1}',
        Deaf => '\u{f2a4}',
        Globe => '\u{f0ac}',
        Torah => '\u{f6a0}',
        SkiingNordic => '\u{f7ca}',
        HeartBroken => '\u{f7a9}',
        Dungeon => '\u{f6d9}',
        Heart => '\u{f004}',
        MortarPestle => '\u{f5a7}',
        Shapes => '\u{f61f}',
        ChevronUp => '\u{f077}',
        FootballBall => '\u{f44e}',
        Guitar => '\u{f7a6}',
        TrafficLight => '\u{f637}',
        AlignJustify => '\u{f039}',
        Fingerprint => '\u{f577}',
        Dog => '\u{f6d3}',
        AlternateComment => '\u{f27a}',
        Users => '\u{f0c0}',
        Drum => '\u{f569}',
        PollH => '\u{f682}',
        PlusSquare => '\u{f0fe}',
        AlternateHeadphones => '\u{f025}',
        AlternateList => '\u{f022}',
        Microchip => '\u{f2db}',
        SmilingFaceWithHeartEyes => '\u{f584}',
        Paw => '\u{f1b0}',
        AlternateArrowCircleLeft => '\u{f359}',
        TruckMonster => '\u{f63b}',
        Hamburger => '\u{f805}',
        Radiation => '\u{f7b9}',
        Mars => '\u{f222}',
        AngleDoubleRight => '\u{f101}',
        ConciergeBell => '\u{f562}',
        Satellite => '\u{f7bf}',
        SearchPlus => '\u{f00e}',
        Stethoscope => '\u{f0f1}',
        Table => '\u{f0ce}',
        Rocket => '\u{f135}',
        TiredFace => '\u{f5c8}',
        PeaceHand => '\u{f25b}',
        Times => '\u{f00d}',
        Bible => '\u{f647}',
        Unlock => '\u{f09c}',
        Swatchbook => '\u{f5c3}',
        Carrot => '\u{f787}',
        AlternateSignOut => '\u{f2f5}',
        HighTemperature => '\u{f769}',
        Biking => '\u{f84a}',
        StepBackward => '\u{f048}',
        Upload => '\u{f093}',
        Syringe => '\u{f48e}',
        AlternateShare => '\u{f1e0}',
        Otter => '\u{f700}',
        CalendarMinus => '\u{f272}',
        Pills => '\u{f484}',
        GlassWhiskey => '\u{f7a0}',
        Lightbulb => '\u{f0eb}',
        AlternateArrows => '\u{f0b2}',
        Key => '\u{f084}',
        CandyCane => '\u{f786}',
        Adjust => '\u{f042}',
        CloudWithHeavyShowers => '\u{f740}',
        WavyMoneyBill => '\u{f53a}',
        Glasses => '\u{f530}',
        Memory => '\u{f538}',
        Download => '\u{f019}',
        Car => '\u{f1b9}',
        Synagogue => '\u{f69b}',
        GripLinesVertical => '\u{f7a5}',
        HollyBerry => '\u{f7aa}',
        MailBulk => '\u{f674}',
        Diagnoses => '\u{f470}',
        CheckSquare => '\u{f14a}',
        Running => '\u{f70c}',
        Blog => '\u{f781}',
        User => '\u{f007}',
        Retweet => '\u{f079}',
        CodeBranch => '\u{f126}',
        SpockHand => '\u{f259}',
        Screwdriver => '\u{f54a}',
        Dragon => '\u{f6d5}',
        ToiletPaper => '\u{f71e}',
        Wifi => '\u{f1eb}',
        ThList => '\u{f00b}',
        FunnelDollar => '\u{f662}',
        MarsStroke => '\u{f229}',
        Joint => '\u{f595}',
        AngleUp => '\u{f106}',
        AreaChart => '\u{f1fe}',
        LowTemperature => '\u{f76b}',
        PieChart => '\u{f200}',
        FolderPlus => '\u{f65e}',
        Ban => '\u{f05e}',
        Menorah => '\u{f676}',
        AlternateLongArrowDown => '\u{f309}',
        HardHat => '\u{f807}',
        CarSide => '\u{f5e4}',
        Female => '\u{f182}',
        BlenderPhone => '\u{f6b6}',
        Cloud => '\u{f0c2}',
        FileDownload => '\u{f56d}',
        Splotch => '\u{f5bc}',
        Tenge => '\u{f7d7}',
        Server => '\u{f233}',
        HotTub => '\u{f593}',
        LowVision => '\u{f2a8}',
        AlternateMedicalChat => '\u{f7f5}',
        Desktop => '\u{f108}',
        UserAstronaut => '\u{f4fb}',
        IdentificationCard => '\u{f2c2}',
        Paperclip => '\u{f0c6}',
        Sync => '\u{f021}',
        PaintBrush => '\u{f1fc}',
        Gifts => '\u{f79c}',
        Mercury => '\u{f223}',
        CalendarCheck => '\u{f274}',
        BandAid => '\u{f462}',
        Moon => '\u{f186}',
        Ruler => '\u{f545}',
        Feather => '\u{f52d}',
        Microscope => '\u{f610}',
        AirFreshener => '\u{f5d0}',
        ChessPawn => '\u{f443}',
        ShuttleVan => '\u{f5b6}',
        Calendar => '\u{f073}',
        File => '\u{f15b}',
        SimCard => '\u{f7c4}',
        ArrowCircleUp => '\u{f0aa}',
        Venus => '\u{f221}',
        Gamepad => '\u{f11b}',
        ParachuteBox => '\u{f4cd}',
        Suitcase => '\u{f0f2}',
        PaintRoller => '\u{f5aa}',
        MugHot => '\u{f7b6}',
        Indent => '\u{f03c}',
        PhoneVolume => '\u{f2a0}',
        AlternateCompressArrows => '\u{f78c}',
        Clock => '\u{f017}',
        Magic => '\u{f0d0}',
        Spinner => '\u{f110}',
        ShekelSign => '\u{f20b}',
        Sun => '\u{f185}',
        Share => '\u{f064}',
        AmericanSignLanguageInterpreting => '\u{f2a3}',
        Cross => '\u{f654}',
        SortAlphabeticalDown => '\u{f15d}',
        HandPointingUp => '\u{f0a6}',
        Flask => '\u{f0c3}',
        UserCircle => '\u{f2bd}',
        Vials => '\u{f493}',
        JournalOfTheWhills => '\u{f66a}',
        Plus => '\u{f067}',
        AlternateMapMarker => '\u{f041}',
        Bong => '\u{f55c}',
        SprayCan => '\u{f5bd}',
        EnvelopeOpen => '\u{f2b6}',
        Store => '\u{f54e}',
        CompactDisc => '\u{f51f}',
        UniversalAccess => '\u{f29a}',
        Print => '\u{f02f}',
        Wallet => '\u{f555}',
        Compress => '\u{f066}',
        HandWithMiddleFingerRaised => '\u{f806}',
        AlternateUndo => '\u{f2ea}',
        Question => '\u{f128}',
        AlternativeTrashRestore => '\u{f82a}',
        IndianRupeeSign => '\u{f156}',
        AlternateSortAlphabeticalDown => '\u{f881}',
        Prescription => '\u{f5b1}',
        CaretRight => '\u{f0da}',
        Road => '\u{f018}',
        AlternatePencil => '\u{f303}',
        GlassCheers => '\u{f79f}',
        Vial => '\u{f492}',
        AlternateMicrophone => '\u{f3c9}',
        AlternateMapMarked => '\u{f5a0}',
        Nurse => '\u{f82f}',
        Pen => '\u{f304}',
        Edit => '\u{f044}',
        CaretDown => '\u{f0d7}',
        ChessKnight => '\u{f441}',
        AlternatePhone => '\u{f879}',
        BasketballBall => '\u{f434}',
        FilePrescription => '\u{f572}',
        CardboardVr => '\u{f729}',
        Circle => '\u{f111}',
        HorizontalSliders => '\u{f1de}',
        AlternateMoneyCheck => '\u{f53d}',
        Tram => '\u{f7da}',
        CloudWithMoonAndRain => '\u{f73c}',
        WordFile => '\u{f1c2}',
        Bullseye => '\u{f140}',
        Tree => '\u{f1bb}',
        LessThanEqualTo => '\u{f537}',
        Chalkboard => '\u{f51b}',
        ToggleOff => '\u{f204}',
        Signal => '\u{f012}',
        CircleNotched => '\u{f1ce}',
        Hippo => '\u{f6ed}',
        EnvelopeSquare => '\u{f199}',
        FileSignature => '\u{f573}',
        AlternateFile => '\u{f15c}',
        DiceThree => '\u{f527}',
        FlushedFace => '\u{f579}',
        Dumbbell => '\u{f44b}',
        Transgender => '\u{f224}',
        LifeRing => '\u{f1cd}',
        SquareWave => '\u{f83e}',
        AlternateWavyMoneyBill => '\u{f53b}',
        AudioDescription => '\u{f29e}',
        Frog => '\u{f52e}',
        CaretSquareRight => '\u{f152}',
        RemoveFormat => '\u{f87d}',
        Bicycle => '\u{f206}',
        PowerOff => '\u{f011}',
        TeethOpen => '\u{f62f}',
        PlaneDeparture => '\u{f5b0}',
        Inbox => '\u{f01c}',
        Parking => '\u{f540}',
        PersonEnteringBooth => '\u{f756}',
        RulerCombined => '\u{f546}',
        WineBottle => '\u{f72f}',
        Backspace => '\u{f55a}',
        HourglassStart => '\u{f251}',
        BeamingFaceWithSmilingEyes => '\u{f5b8}',
        Pastafarianism => '\u{f67b}',
        Crop => '\u{f125}',
        DrumstickWithBiteTakenOut => '\u{f6d7}',
        Republican => '\u{f75e}',
        Bomb => '\u{f1e2}',
        WiredNetwork => '\u{f6ff}',
        Crown => '\u{f521}',
        UsersCog => '\u{f509}',
        QuestionCircle => '\u{f059}',
        RemoveUser => '\u{f235}',
        TintSlash => '\u{f5c7}',
        Eye => '\u{f06e}',
        Hammer => '\u{f6e3}',
        PdfFile => '\u{f1c1}',
        Signature => '\u{f5b7}',
        FrowningFace => '\u{f119}',
        FlagCheckered => '\u{f11e}',
        UserCheck => '\u{f4fc}',
        Bath => '\u{f2cd}',
        WindowMinimize => '\u{f2d1}',
        Podcast => '\u{f2ce}',
        Microphone => '\u{f130}',
        TheaterMasks => '\u{f630}',
        Spa => '\u{f5bb}',
        UserInjured => '\u{f728}',
        RegisteredTrademark => '\u{f25d}',
        Blender => '\u{f517}',
        SatelliteDish => '\u{f7c0}',
        CommentDots => '\u{f4ad}',
        WinkingFaceWithTongue => '\u{f58b}',
        Cog => '\u{f013}',
        Futbol => '\u{f1e3}',
        SearchMinus => '\u{f010}',
        DamagedHouse => '\u{f6f1}',
        IceCream => '\u{f810}',
        RetroCamera => '\u{f083}',
        ChevronCircleLeft => '\u{f137}',
        EyeDropper => '\u{f1fb}',
        TShirt => '\u{f553}',
        DrawPolygon => '\u{f5ee}',
        Church => '\u{f51d}',
        Dice => '\u{f522}',
        Thermometer => '\u{f491}',
        Bone => '\u{f5d7}',
        AlternateMicrophoneSlash => '\u{f539}',
        MedicalNotes => '\u{f481}',
        Clone => '\u{f24d}',
        ShareSquare => '\u{f14d}',
        IBeamCursor => '\u{f246}',
        LaptopMedical => '\u{f812}',
        HourglassHalf => '\u{f252}',
        Broom => '\u{f51a}',
        ChessBishop => '\u{f43a}',
        SdCard => '\u{f7c2}',
        GreaterThanEqualTo => '\u{f532}',
        Brush => '\u{f55d}',
        Gift => '\u{f06b}',
        Toolbox => '\u{f552}',
        Code => '\u{f121}',
        Mouse => '\u{f8cc}',
        VectorSquare => '\u{f5cb}',
        AddToShoppingCart => '\u{f217}',
        PhoneSlash => '\u{f3dd}',
        ShippingFast => '\u{f48b}',
        BroadcastTower => '\u{f519}',
        Copyright => '\u{f1f9}',
        Plug => '\u{f1e6}',
        SpaceShuttle => '\u{f197}',
        Bell => '\u{f0f3}',
        Teeth => '\u{f62e}',
        Mosque => '\u{f678}',
        Monument => '\u{f5a6}',
        AlternatePen => '\u{f305}',
        Doctor => '\u{f0f0}',
        SortNumericUp => '\u{f163}',
        AngleDoubleDown => '\u{f103}',
        FileImport => '\u{f56f}',
        Stroopwafel => '\u{f551}',
        PaperHand => '\u{f256}',
        DoorOpen => '\u{f52b}',
        Dumpster => '\u{f793}',
        PlusCircle => '\u{f055}',
        ScissorsHand => '\u{f257}',
        FileInvoiceWithUsDollar => '\u{f571}',
        LightningBolt => '\u{f0e7}',
        Bookmark => '\u{f02e}',
        Atlas => '\u{f558}',
        Stop => '\u{f04d}',
        AlternateWineGlas => '\u{f5ce}',
        Battery34Full => '\u{f241}',
        GrimacingFace => '\u{f57f}',
        HandHolding => '\u{f4bd}',
        Weight => '\u{f496}',
        AlternateLevelUp => '\u{f3bf}',
        Television => '\u{f26c}',
        Portrait => '\u{f3e0}',
        ClipboardList => '\u{f46d}',
        Campground => '\u{f6bb}',
        Ambulance => '\u{f0f9}',
        Passport => '\u{f5ab}',
        Fan => '\u{f863}',
        CheckCircle => '\u{f058}',
        LocationArrow => '\u{f124}',
        AngleDoubleUp => '\u{f102}',
        Dolly => '\u{f472}',
        GolfBall => '\u{f450}',
        DraftingCompass => '\u{f568}',
        Handshake => '\u{f2b5}',
        KiwiBird => '\u{f535}',
        ShoppingBag => '\u{f290}',
        Font => '\u{f031}',
        Bullhorn => '\u{f0a1}',
        Sign => '\u{f4d9}',
        ProjectDiagram => '\u{f542}',
        ChevronLeft => '\u{f053}',
        Directions => '\u{f5eb}',
        AlternateSquareRoot => '\u{f698}',
        SignLanguage => '\u{f2a7}',
        BusAlt => '\u{f55e}',
        Child => '\u{f1ae}',
        Couch => '\u{f4b8}',
        CarCrash => '\u{f5e1}',
        DiceTwo => '\u{f528}',
        Receipt => '\u{f543}',
        ChevronCircleUp => '\u{f139}',
        Phone => '\u{f095}',
        Recycle => '\u{f1b8}',
        Hiking => '\u{f6ec}',
        GrinningFaceWithSweat => '\u{f583}',
        Spider => '\u{f717}',
        Beer => '\u{f0fc}',
        IdentificationBadge => '\u{f2c1}',
        Biohazard => '\u{f780}',
        VolumeDown => '\u{f027}',
        UnitedStatesOfAmericaFlag => '\u{f74d}',
        Cheese => '\u{f7ef}',
        Columns => '\u{f0db}',
        AlternateIdentificationCard => '\u{f47f}',
        TruckSide => '\u{f63c}',
        RaisedFist => '\u{f6de}',
        Hanukiah => '\u{f6e6}',
        Smoking => '\u{f48d}',
        RockHand => '\u{f255}',
        HangingWeight => '\u{f5cd}',
        CookieBite => '\u{f564}',
        Stream => '\u{f550}',
        Skiing => '\u{f7c9}',
        ToriiGate => '\u{f6a1}',
        FaceWithRollingEyes => '\u{f5a5}',
        Coffee => '\u{f0f4}',
        AlternateLongArrowRight => '\u{f30b}',
        UserClock => '\u{f4fd}',
        OilCan => '\u{f613}',
        CloudWithMoon => '\u{f6c3}',
        Superscript => '\u{f12b}',
        AlternateTrash => '\u{f2ed}',
        Expand => '\u{f065}',
        Infinity => '\u{f534}',
    }
}

impl From<Icons> for char {
    fn from(icon: Icons) -> Self {
        icon_unicode(icon)
    }
}

impl From<Icons> for String {
    fn from(icon: Icons) -> Self {
        format!("{}", icon_unicode(icon))
    }
}

impl std::fmt::Display for Icons {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", icon_unicode(*self))
    }
}